name: C++ CI

on:
  push:
    branches: [ main, design ]
  pull_request:
    branches: [ main, design ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile C++ 2017
        run: make
  metrics:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Design metrics
        uses: sarnold/cccc-action@0.3