name: C++ CI

on:
  push:
    branches: [ main, design ]
  pull_request:
    branches: [ main, design ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential g++ cmake git
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker container
        run: |
          docker build -t cpp-analysis .
          docker run -it cpp-analysis