name: C++ CI

on:
  push:
    branches: [ main, design ]
  pull_request:
    branches: [ main, design ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential g++ cmake git-all pmccabe 
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile C++ 2017
        run: |
          export SRC_DIR=$PWD
          make
  metrics:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install and run PMcCabe
        run: pmccabe *.cpp -v