name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile C++ 2017
        run: |
          export SRC_DIR=$PWD
          make
  analyze:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install linting dependencies
        run: |
          sudo apt-get update 
          sudo apt-get -qq --assume-yes install cppcheck
      - name: Analyze design
        run: |
          ls
          cppcheck --std=c++17 $SRC_DIR