name: C++ CI

on:
  push:
    branches: [ main, design ]
  pull_request:
    branches: [ main, design ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile C++ 2017
        run: |
          export SRC_DIR=$PWD
          make
  metrics:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install and run cccc
        run: |
          sudo apt update
          sudo apt install cccc
          cccc --lang=c++ *.cpp